# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SantanderTesteiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SantanderTesteiOS
  pod 'Cartography', '~> 3.0'
  pod 'AKMaskField' #Textfield with mask
  pod 'IQKeyboardManagerSwift', '~> 5.0'

  target 'SantanderTesteiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SantanderTesteiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
